### ISSUE TITLE
signJars fails withZipException: duplicate entry: com/foo/ejb-jar.xml

### ISSUE THREAD

**Issue by farrukhnajmi** [tschulte/gradle-jnlp-plugin#37]
I have a very complex legacy project that is being converted to use the gradle-jnlp-plugin. I have two sibling sub-projects that are both very similar. However, obe project builds fine and the other fails with log and stack trace below. 

One observation is that even though the two projects have very similar dependencies the project that works creates many dependency jars to sign while the project that does not work seem to only be attempting to sign two jars.

Any suggestions what I should look for? I have looked for duplicate entries in relevant jars but am not seeing it. Is there a way to avoid this?

```
21:14:27.901 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
21:14:27.901 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
21:14:27.901 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
21:14:27.901 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':gem-5000-ui:signJars'.
21:14:27.901 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.reflect.UndeclaredThrowableException (no error message)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gem-5000-ui:signJars'.
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
21:14:27.902 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
21:14:27.903 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.reflect.UndeclaredThrowableException
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:504)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinPool.invoke(ForkJoinPool.java:1492)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.extra166y.ParallelArrayWithMapping.apply(ParallelArrayWithMapping.java:48)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.extra166y.ParallelArray.apply(ParallelArray.java:329)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.pa.GParsPoolUtilHelper.eachParallelPA(GParsPoolUtilHelper.groovy:192)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPoolUtil.eachParallel(GParsPoolUtil.java:358)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at de.gliderpilot.gradle.jnlp.SignJarsTask$_signJars_closure3.doCall(SignJarsTask.groovy:44)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy:174)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPool.withExistingPool(GParsPool.groovy:173)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPool$withExistingPool$1.callStatic(Unknown Source)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:145)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPool$withPool$0.callStatic(Unknown Source)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:121)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.GParsPool$withPool.call(Unknown Source)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at de.gliderpilot.gradle.jnlp.SignJarsTask.signJars(SignJarsTask.groovy:43)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 78 more
21:14:27.904 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.reflect.UndeclaredThrowableException
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.sun.proxy.$Proxy79.op(Unknown Source)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.extra166y.AbstractParallelAnyArray$OUPap.leafApply(AbstractParallelAnyArray.java:640)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.extra166y.PAS$FJOApply.atLeaf(PAS.java:147)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:108)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.util.zip.ZipException: duplicate entry: com/ilrd/gem/g5k/dm/ejb-jar.xml
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java_util_jar_JarOutputStream$putNextEntry.call(Unknown Source)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at de.gliderpilot.gradle.jnlp.SignJarsTask$_copyUnsignAndAlterManifest_closure7_closure13.doCall(SignJarsTask.groovy:91)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at de.gliderpilot.gradle.jnlp.SignJarsTask$_copyUnsignAndAlterManifest_closure7.doCall(SignJarsTask.groovy:89)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at de.gliderpilot.gradle.jnlp.SignJarsTask.copyUnsignAndAlterManifest(SignJarsTask.groovy:88)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at de.gliderpilot.gradle.jnlp.SignJarsTask$_signJars_closure3_closure9.doCall(SignJarsTask.groovy:45)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at groovyx.gpars.pa.GParsPoolUtilHelper$_eachParallelPA_closure8.doCall(GParsPoolUtilHelper.groovy:192)
21:14:27.905 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 10 more
```

**Comment by farrukhnajmi** [comment]
I believe this could be a concurrency bug in the plugin. My reasons for belief are:

- the stack trace includes the following from jsr66:

```
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy62.op(Unknown Source)
	at groovyx.gpars.extra166y.AbstractParallelAnyArray$OUPap.leafApply(AbstractParallelAnyArray.java:640)
	at groovyx.gpars.extra166y.PAS$FJOApply.atLeaf(PAS.java:147)
	at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:108)
	at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
	at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
	at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
	at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
```

- The jar being signed according to output comment does not even have the duplicate entry

Please let me know what you think. I will use your guidance to find a fix and contribute a patch. Thanks.

**Comment by tschulte** [comment]
The issue is that some jars in fact have duplicate entries. You will not see these when using `jar -tf`, but when using java to enumerate the jar entries, you will see the duplicate entries. When trying to copy one JarInputStream to a JarOutputStream, as the plugin does to remove unwanted content from jars, this causes problems, because the JarOutputStream does not allow adding an entry twice.

Using the commandline `jar` tool, you can not generate jars with duplicate entries, but I think ant and maven can sometimes create such jars. I once had a spring jar with duplicate entries. 

I think it is OK to skip duplicate entries and issue a warning on the console.

**Comment by farrukhnajmi** [comment]
In that case please consider my revised patch for fixing this issue in previous comment. The only change I made is to remove stack trace as it adds a lot of clutter. If you prefer the stack trace feel free to add it back in. Thanks for your terrific help and a great plugin.

**Comment by tschulte** [comment]
Can you please tell me which jar file is causing the trouble, so I can write a test case for this?

**Comment by farrukhnajmi** [comment]
Its actually one of our product proprietary jars. The log message was misleading in SignJarsTask.groovy and my patch addresses that as well. Perhaps you can take any jar and manually add duplicate entry to it? Thanks very much!

**Comment by tschulte** [comment]
I added a task input to the signJars task. Now you can exclude duplicate zip entries by defining

```groovy
tasks.signJars {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
```

The default is to INCLUDE them (which is the behaviour as before).
