### ISSUE TITLE
How to publish a private version of plugin to a private artifactory server

### ISSUE THREAD

**Issue by farrukhnajmi** [tschulte/gradle-jnlp-plugin#38]
I need to build my own private version of this plugin and publish it to my private artifactory repo. For context see:

https://github.com/tschulte/gradle-jnlp-plugin/issues/36

I tried the following:

gradlew -i -s  -Pversion=1.0.1-fnajmi publishPlugins

I get the exception:

```
Caused by: java.lang.RuntimeException: Invalid version '1.0.1-develop-SNAPSHOT'. Set 'version' property string must with a string that: 1) is more than 1 and less than 20 characters long; 2) includes a number; and 3) that matches the regular expression: [a-zA-Z0-9\-\.\[\]\:\+]*
	at com.gradle.publish.PluginPublishValidator.validateVersion(PluginPublishValidator.java:157)
	at com.gradle.publish.PluginPublishValidator.validatePluginConfig(PluginPublishValidator.java:127)
	at com.gradle.publish.PluginPublishValidator.validateBundle(PluginPublishValidator.java:91)
	at com.gradle.publish.PublishTask.publish(PublishTask.java:48)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
```

It seems it is due to the de.gliderpilot.semantic-release plugin not allowing me to do so. Also when I pub

I am looking for answers to the following:

- How can I bypass  de.gliderpilot.semantic-release plugin and set my own version

- How can I deploy the plugin to my private artifcatory.

It would be nice to have some documentation targeted for developers of the project where this info can be kept.

I am really stuck and would appreciate some help or else I will have to unwind a lot of work to use this plugin and go back to the dark ages of manually assembling the jnlp package.

**Comment by farrukhnajmi** [comment]
I have been able to work around this issue by building the project using:

gradlew -i -s -Pversion=1.0.1-fnajmi assemble

and then publishing it to my private artifactory using artifactory web console. I still think it would help folks in a similar situation if there was a README file for developers.
