### ISSUE TITLE
Warning when running with Gradle 5.0

### ISSUE THREAD

**Issue by amake** [tschulte/gradle-jnlp-plugin#56]
When executing tasks from this plugin I get the following message:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings
```

With `./gradlew assembleWebstartDist --warning-mode all --debug --stacktrace` I get the following stack trace:

```
10:11:18.286 [WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler] The configuration :jnlp was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.0/userguide/troubleshooting_dependency_resolution.html#configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:521)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:511)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
        at de.gliderpilot.gradle.jnlp.AbstractCopyJarsTask.newName(AbstractCopyJarsTask.groovy:33)
        at de.gliderpilot.gradle.jnlp.AbstractCopyJarsTask$newName$5.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at de.gliderpilot.gradle.jnlp.SignJarsTask.copyUnsignAndAlterManifest(SignJarsTask.groovy:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at de.gliderpilot.gradle.jnlp.SignJarsTask$_signJars_closure3$_closure10.doCall(SignJarsTask.groovy:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at groovyx.gpars.pa.GParsPoolUtilHelper$_eachParallelPA_closure8.doCall(GParsPoolUtilHelper.groovy:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
        at com.sun.proxy.$Proxy64.op(Unknown Source)
        at groovyx.gpars.extra166y.AbstractParallelAnyArray$OUPap.leafApply(AbstractParallelAnyArray.java:640)
        at groovyx.gpars.extra166y.PAS$FJOApply.atLeaf(PAS.java:147)
        at groovyx.gpars.extra166y.PAS$FJBase.internalCompute(PAS.java:118)
        at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:106)
        at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
        at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
        at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:733)
        at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
        at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
```

I think the issue must be within the plugin rather than in my code, but please correct me if I'm wrong.

**Comment by tschulte** [comment]
Yes, I think this is an issue with this plugin. The SignJarsTask signs the jars in parallel and does access the configuration from within the signing threads. This must be refactored to prevent this warning.

**Comment by amake** [comment]
Gradle 6.0 is out, and because of this issue the plugin is unfortunately not usable.

**Comment by ChristianCiach** [comment]
I am trying to make this plugin compatible with Gradle 6.0, but there is a major roadblock because of missing APIs: https://github.com/gradle/gradle/issues/2678#issuecomment-554988410

This plugin uses Ant to sign jar files, but Gradle is missing an API to access Ant from within worker threads. We could probably call the "jarsigner" binary directly without using Ant, but I didn't try this yet.

We could also just remove parallel jar signing as a quick workaround, but this would increase build time if you sign many jar files.

**Comment by amake** [comment]
I would prefer slower builds to being unable to move to Gradle 6.0 ever.

If it's easy to decide between parallel and serial execution at runtime, you could keep it parallel for pre-6.0 to limit the impact.

**Comment by ChristianCiach** [comment]
I was able to make the plugin work by calling the jarsigner binary directly, without using Ant. Unfortunately, to make this work, I had to remove a lot of functionality from the plugin that I don't need. Keeping all these functions intact would require a lot of additional work, but I just cannot invest the time for this.

**Comment by tschulte** [comment]
Currently I don't have much time available to spend on fixing this issue. 

I tried to add support to running with higher gradle versions during the integration tests. But for this I need to upgrade nebula-test, but that requires to upgrade the used gradle version itself, and that requires to change even more.

I will try to invest some more time tonight and at least push my changes to a branch so you might take over from there.

We might need to remove support for older gradle versions. This major change would give us the opportunity to remove deprecated functionality. Plus we should deprecate pack200 support and change it to be disabled by default, since pack200 is deprecated in the jdk.

**Comment by ChristianCiach** [comment]
Someone over at the Gradle issue tracker someone gave me the advise to use the `AntBuilder` directly, without using Gradles API (that is inaccessable from withing worker threads). Doing it this way, I probably can restore all the features of the plugin. 

If there is interest, I can push my changes as a PR or something.

**Comment by tschulte** [comment]
I just pushed a quick fix, without having it in the automatic integration tests. I did a manual test with gradle 6 though.

**Comment by tschulte** [comment]
@ChristianCiach sure, you can create a PR, and we can discuss it.

**Comment by ChristianCiach** [comment]
Ah, so you now prevent the issue by calling any Gradle API before starting the threads. That's clever :)

**Comment by tschulte** [comment]
v1.2.6 just got released by travis. Please let me know if this fixes your problems.

**Comment by amake** [comment]
It works for me. Thanks!
